server {
    listen 80;
    server_name localhost;

    # Serve frontend estático
    root /usr/share/nginx/html;
    index index.html;

    # Proxy para o backend Python/Flask
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~* \.(?:js|css)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        try_files $uri =404;
    }

    # SPA fallback
    location / {
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri $uri/ /index.html;
    }
}
